service: dt60-win

provider:
  name: azure
  runtime: dotnet6.0
  region: West Europe
  prefix: int
  stage: qa
  apim: true
  environment:
    VARIABLE_FOO: 'foo'

plugins:
  - serverless-azure-functions

functions:
  hello:
    handler: hello
    events:
      - http: true
        methods:
          - GET
        authLevel: anonymous